language: java
sudo: false
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: false
cache:
  directories:
    - "$HOME/.m2"
install: true
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
    - jdk: openjdk15
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea
script:
  - "./mvnw clean install -U -Dmaven.javadoc.skip=false"
  - "if [ \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then ./mvnw sonar:sonar -Dsonar.projectKey=cyanpotion_x8l -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.log.level=DEBUG -Dsonar.sources=src/main/ -Dsonar.language=java -Dsonar.java.source=1.8 -Dsonar.sourceEncoding=UTF-8 -Dsonar.java.binaries=target/classes/ -Dsonar.java.test.binaries=target/test-classes/ -Dsonar.tests=src/test/ -Dsonar.java.coveragePlugin=jacoco -Dsonar.jacoco.reportPaths=target/jacoco.exec -Dsonar.junit.reportPaths=target/surefire-reports/ -Dsonar.login=9f24179f0804925e2647f57ca2effc7a0686d0b7 ; fi"
