language: shell
sudo: true
dist: trusty
before_install: true
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
matrix:
  include:
    - os: windows
script:
  - git clone --depth=1 https://github.com/XenoAmess/java-ci.git
  - (
    echo .\java-ci\7z x """.\java-ci\jdk.7z.001""" -y -aos
    echo set JAVA_HOME=.\java-ci\jdk
    echo set path=%path%;%JAVA_HOME%\bin
    echo .\java-ci\mvnw.cmd clean package -Dmaven.javadoc.skip=false
    ) > java-ci\java-ci-test.cmd
  - java-ci-test.cmd