language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: false
cache:
  directories:
    - "$HOME/.m2"
install: true
matrix:
  include:
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: linux
      jdk: openjdk12
    - os: linux
      jdk: openjdk13
    - os: linux
      jdk: openjdk14
script:
  - "./mvnw clean package -U -Dmaven.javadoc.skip=false"
  - "if [ test \"$TRAVIS_JDK_VERSION\" = \"openjdk12\" ]; then ./mvnw sonar:sonar -Dsonar.projectKey=cyanpotion_x8l -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9f24179f0804925e2647f57ca2effc7a0686d0b7 ; fi"
