language: shell
sudo: true
dist: trusty
before_install: true
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
matrix:
  include:
    - os: windows
script:
  - git clone --depth=1 https://github.com/XenoAmess/java-ci.git
  - xcopy .\java-ci\*.* .\ /s/d
  - test.cmd