language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
git:
  depth: 1
cache:
  directories:
    - $HOME/.m2
install: true
env:
  global:
matrix:
  include:
    - os: linux
      jdk: openjdk12
script:
  - ./mvnw clean package -Dmaven.javadoc.skip=false
  - ./mvnw sonar:sonar -Dsonar.projectKey=cyanpotion_x8l -Dsonar.organization=cyanpotion -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=9f24179f0804925e2647f57ca2effc7a0686d0b7
